// <auto-generated />
using System;
using CosmoManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CosmoManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CosmoManager.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CosmoManager.Models.DataSyncState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastErrorAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("DataSyncStates");
                });

            modelBuilder.Entity("CosmoManager.Models.InfoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("date");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Gradient")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DateStart");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Type");

                    b.ToTable("InfoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Платформа",
                            Content = "# CosmoManager 1.0 — история создания\r\n\r\nВсё началось с идеи создать удобную платформу для управления кланом, событиями, турнирами и статистикой.\r\n\r\n---\r\n\r\n## Основная идея\r\n\r\nCosmoManager объединяет новости, события, турниры, аналитику и инструменты для кланов в одном веб-приложении.\r\n\r\n## Возможности\r\n\r\n- управление клановой информацией;\r\n- просмотр новостей и событий;\r\n- работа с турнирами;\r\n- аналитика и справочные разделы.",
                            CreatedAtUtc = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateStart = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Excerpt = "Рассказываем о том, как появился CosmoManager — от первой идеи до полноценной платформы для кланов Мир Танков.",
                            Gradient = "linear-gradient(135deg, #1a0540 0%, #582BBA 60%, #835de4 100%)",
                            IsPublished = true,
                            Title = "CosmoManager 1.0: история создания проекта",
                            Type = "News"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Обновление",
                            Content = "## Обновление 1.1\r\n\r\nВ этом обновлении улучшена стабильность работы платформы, оптимизирована загрузка страниц и подготовлена основа для новых модулей.\r\n\r\n---\r\n\r\n## Основные изменения\r\n\r\n- улучшена работа страниц новостей и событий;\r\n- добавлена подготовка к административному управлению контентом;\r\n- оптимизирована структура API.",
                            CreatedAtUtc = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateStart = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Excerpt = "Улучшена скорость загрузки, добавлены фильтры и исправлены найденные ошибки.",
                            Gradient = "linear-gradient(135deg, #0f1e40 0%, #1a3a6b 50%, #2d5bbf 100%)",
                            IsPublished = true,
                            Title = "Обновление платформы 1.1 — что нового",
                            Type = "News"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Гайд",
                            Content = "## Провинции глобальной карты\r\n\r\nПри выборе провинций важно учитывать активность клана, время боёв, доходность территории и состав команды.\r\n\r\n---\r\n\r\n## Рекомендации\r\n\r\n- начинать с менее спорных направлений;\r\n- удерживать провинции с высокой доходностью;\r\n- заранее планировать составы на бои.",
                            CreatedAtUtc = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateStart = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Excerpt = "Подробный разбор: какие провинции брать первыми, как удержать доходные точки и когда отступать.",
                            Gradient = "linear-gradient(135deg, #200a00 0%, #8a2200 50%, #FF5000 100%)",
                            IsPublished = true,
                            Title = "Гайд по провинциям глобальной карты",
                            Type = "News"
                        },
                        new
                        {
                            Id = 101,
                            Category = "Клан",
                            Content = "# Сезон «Стальная воля»\r\n\r\nГлобальная кампания, в которой кланы соревнуются за контроль над провинциями мировой карты.\r\n\r\n---\r\n\r\n## Условия участия\r\n\r\n- клан должен иметь активный состав;\r\n- необходимо зарегистрироваться до начала сезона;\r\n- бои проходят по расписанию глобальной карты.",
                            CreatedAtUtc = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateEnd = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Excerpt = "Кланы сражаются за провинции. Победители получат золото, декали и уникальный стиль «Стальная воля».",
                            Gradient = "linear-gradient(135deg, #1a0540 0%, #582BBA 60%, #835de4 100%)",
                            IsPublished = true,
                            Status = "active",
                            Title = "Сезон Глобальной карты «Стальная воля»",
                            Type = "Event"
                        },
                        new
                        {
                            Id = 102,
                            Category = "Турнир",
                            Content = "# Железный кулак #12\r\n\r\nЕженедельный турнир для кланов в формате 7/42.\r\n\r\n---\r\n\r\n## Формат\r\n\r\n- групповая стадия;\r\n- плей-офф;\r\n- финальные бои;\r\n- награды для лучших команд.",
                            CreatedAtUtc = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateEnd = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Excerpt = "Еженедельный клановый турнир в формате 7/42. Призовой фонд 10 000 золота.",
                            Gradient = "linear-gradient(135deg, #200a00 0%, #8a2200 50%, #FF5000 100%)",
                            IsPublished = true,
                            Status = "active",
                            Title = "Турнир «Железный кулак» #12",
                            Type = "Event"
                        },
                        new
                        {
                            Id = 103,
                            Category = "Турнир",
                            Content = "# Кубок Весны 2025\r\n\r\nСамый крупный турнир первого полугодия. Участвуют кланы со всего СНГ.\r\n\r\n---\r\n\r\n## Основная информация\r\n\r\n- формат: 15 на 15;\r\n- количество участников ограничено;\r\n- регистрация открывается заранее;\r\n- победители получают денежные и внутриигровые награды.",
                            CreatedAtUtc = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateEnd = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Excerpt = "Крупный весенний турнир с призовым фондом 200 000 ₽. Регистрация открывается 25 марта.",
                            Gradient = "linear-gradient(135deg, #0a200a 0%, #145214 50%, #22c55e 100%)",
                            IsPublished = true,
                            Status = "soon",
                            Title = "Кубок Весны 2025",
                            Type = "Event"
                        });
                });

            modelBuilder.Entity("CosmoManager.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CosmoManager.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Classes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("InitialParticipants")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStream")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("OpenForAll")
                        .HasColumnType("boolean");

                    b.Property<string>("PrizeText")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegEnd")
                        .HasColumnType("date");

                    b.Property<DateTime>("RegStart")
                        .HasColumnType("date");

                    b.Property<int>("ReserveSize")
                        .HasColumnType("integer");

                    b.Property<string>("Sponsor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StreamUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TeamSize")
                        .HasColumnType("integer");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classes = "BO3",
                            CreatedAtUtc = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateEnd = new DateTime(2025, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Еженедельный клановый турнир в формате 7x7. Только для участников клана IEVGI и приглашённых команд.",
                            EventId = 102,
                            Format = "7x7",
                            InitialParticipants = 12,
                            IsPublished = true,
                            IsStream = true,
                            MaxParticipants = 16,
                            Name = "Железный кулак — Весенний сезон",
                            OpenForAll = false,
                            RegEnd = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegStart = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReserveSize = 1,
                            Sponsor = "EVG",
                            Status = "active",
                            StreamUrl = "https://twitch.tv/evg_stream",
                            TeamSize = 7,
                            Tier = 10,
                            Type = "epic"
                        },
                        new
                        {
                            Id = 2,
                            Classes = "BO3,PE",
                            CreatedAtUtc = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateEnd = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Открытый турнир для всех желающих. Формат 15x15, только X уровень. Спонсор — Lesta Games.",
                            EventId = 103,
                            Format = "15x15",
                            InitialParticipants = 18,
                            IsPublished = true,
                            IsStream = true,
                            MaxParticipants = 32,
                            Name = "Кубок Весны 2025",
                            OpenForAll = true,
                            RegEnd = new DateTime(2025, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegStart = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReserveSize = 2,
                            Sponsor = "Lesta Games",
                            Status = "registration",
                            StreamUrl = "https://youtube.com/@cosmomanager",
                            TeamSize = 15,
                            Tier = 10,
                            Type = "legendary"
                        },
                        new
                        {
                            Id = 3,
                            Classes = "ST",
                            CreatedAtUtc = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateEnd = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Небольшой тренировочный турнир для клана EVG. Формат 3x3, любой уровень VI–VIII.",
                            Format = "3x3",
                            InitialParticipants = 6,
                            IsPublished = true,
                            IsStream = false,
                            Name = "Тренировочный 3x3",
                            OpenForAll = false,
                            RegEnd = new DateTime(2025, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegStart = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReserveSize = 1,
                            Status = "upcoming",
                            TeamSize = 3,
                            Tier = 8,
                            Type = "common"
                        });
                });

            modelBuilder.Entity("CosmoManager.Models.TournamentMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentMaps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "/images/maps/lasvile.webp",
                            Name = "Ласвилль",
                            TournamentId = 1
                        },
                        new
                        {
                            Id = 2,
                            Image = "/images/maps/steppes.webp",
                            Name = "Степи",
                            TournamentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Image = "/images/maps/prokhorovka.webp",
                            Name = "Прохоровка",
                            TournamentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Image = "/images/maps/prokhorovka.webp",
                            Name = "Прохоровка",
                            TournamentId = 2
                        },
                        new
                        {
                            Id = 5,
                            Image = "/images/maps/himmelsdorf.webp",
                            Name = "Химмельсдорф",
                            TournamentId = 2
                        },
                        new
                        {
                            Id = 6,
                            Image = "/images/maps/steppes.webp",
                            Name = "Степи",
                            TournamentId = 3
                        });
                });

            modelBuilder.Entity("CosmoManager.Models.TournamentPrize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Text")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentPrizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000,
                            Place = "place1",
                            TournamentId = 1,
                            Type = "gold"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3000,
                            Place = "place2",
                            TournamentId = 1,
                            Type = "gold"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1500,
                            Place = "place3",
                            TournamentId = 1,
                            Type = "gold"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 500,
                            Place = "others",
                            TournamentId = 1,
                            Type = "gold"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 200000,
                            Place = "place1",
                            TournamentId = 2,
                            Type = "rub"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 100000,
                            Place = "place2",
                            TournamentId = 2,
                            Type = "rub"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 50000,
                            Place = "place3",
                            TournamentId = 2,
                            Type = "rub"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 10000,
                            Place = "others",
                            TournamentId = 2,
                            Type = "rub"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 1000,
                            Place = "place1",
                            TournamentId = 3,
                            Type = "gold"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 500,
                            Place = "place2",
                            TournamentId = 3,
                            Type = "gold"
                        });
                });

            modelBuilder.Entity("CosmoManager.Models.TournamentRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Contact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("TournamentId", "AppUserId")
                        .IsUnique();

                    b.ToTable("TournamentRegistrations");
                });

            modelBuilder.Entity("CosmoManager.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsCollector")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTechTree")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nation");

                    b.HasIndex("Tier");

                    b.HasIndex("Type");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("CosmoManager.Models.VehicleMark", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<int?>("Moe100")
                        .HasColumnType("integer");

                    b.Property<int?>("Moe65")
                        .HasColumnType("integer");

                    b.Property<int?>("Moe85")
                        .HasColumnType("integer");

                    b.Property<int?>("Moe95")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VehicleId");

                    b.ToTable("VehicleMarks");
                });

            modelBuilder.Entity("CosmoManager.Models.VehicleMastery", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.Property<int?>("Deg1")
                        .HasColumnType("integer");

                    b.Property<int?>("Deg2")
                        .HasColumnType("integer");

                    b.Property<int?>("Deg3")
                        .HasColumnType("integer");

                    b.Property<int?>("Master")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VehicleId");

                    b.ToTable("VehicleMasteries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CosmoManager.Models.RefreshToken", b =>
                {
                    b.HasOne("CosmoManager.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CosmoManager.Models.Tournament", b =>
                {
                    b.HasOne("CosmoManager.Models.InfoItem", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CosmoManager.Models.TournamentMap", b =>
                {
                    b.HasOne("CosmoManager.Models.Tournament", "Tournament")
                        .WithMany("Maps")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("CosmoManager.Models.TournamentPrize", b =>
                {
                    b.HasOne("CosmoManager.Models.Tournament", "Tournament")
                        .WithMany("Prizes")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("CosmoManager.Models.TournamentRegistration", b =>
                {
                    b.HasOne("CosmoManager.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmoManager.Models.Tournament", "Tournament")
                        .WithMany("Registrations")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CosmoManager.Models.VehicleMark", b =>
                {
                    b.HasOne("CosmoManager.Models.Vehicle", "Vehicle")
                        .WithOne("Mark")
                        .HasForeignKey("CosmoManager.Models.VehicleMark", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CosmoManager.Models.VehicleMastery", b =>
                {
                    b.HasOne("CosmoManager.Models.Vehicle", "Vehicle")
                        .WithOne("Mastery")
                        .HasForeignKey("CosmoManager.Models.VehicleMastery", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CosmoManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CosmoManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CosmoManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CosmoManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CosmoManager.Models.Tournament", b =>
                {
                    b.Navigation("Maps");

                    b.Navigation("Prizes");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("CosmoManager.Models.Vehicle", b =>
                {
                    b.Navigation("Mark");

                    b.Navigation("Mastery");
                });
#pragma warning restore 612, 618
        }
    }
}
